; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = position_sweep

[env]
platform = teensy
board = teensy40
; Remove -DNU_TELEMETRY and -DUSB_DUAL_SERIAL together to disable live telemetry
build_flags = -O2 -DNU_TELEMETRY -DUSB_DUAL_SERIAL
build_unflags = -Os
framework = arduino
lib_deps = https://github.com/luni64/TeensyTimerTool.git
    https://github.com/PaulStoffregen/SPI.git
monitor_speed = 115200

[env:position_sweep]
build_src_filter = +<demos/position_sweep.cpp>

[env:one_shot]
build_src_filter = +<demos/one_shot.cpp>
